const express = require('express')
const router = express.Router()
const productController = require('../controllers/api/productController')
const cartController = require('../controllers/api/cartController')
const orderController = require('../controllers/api/orderController')
const adminController = require('../controllers/api/adminController')
const userController = require('../controllers/api/userController')
const upload = require('../middleware/multer')
const { authenticated, authenticatedAdmin } = require('../middleware/api-auth')



router.get('/products', productController.getProducts)
router.get('/products/:id', productController.getProduct)
router.get('/carts', cartController.getCarts)
router.post('/carts', cartController.postCart)
router.get('/carts/checkout', authenticated, cartController.checkoutCart)
router.post('/carts/cartItem/:id/add', authenticated, cartController.addCartItem)
router.post('/carts/cartItem/:id/sub', authenticated, cartController.subCartItem)
router.delete('/carts/cartItem/:id/delete', authenticated, cartController.deleteCartItem)
router.get('/orders', authenticated, orderController.getOrder)
router.post('/orders', authenticated, orderController.postOrder)
router.put('/orders/:id/cancel', authenticated, orderController.cancelOrder)
router.get('/orders/:id/payment', authenticated, orderController.getPayment)

router.get('/admin/products', authenticated, authenticatedAdmin, adminController.getProducts)
router.get('/admin/product/add', authenticated, authenticatedAdmin, adminController.addProduct)
router.get('/admin/product/:id', authenticated, authenticatedAdmin, adminController.getProduct)
router.post('/admin/product', upload.single('image'), adminController.postProduct)
router.delete('/admin/product/:id/delete', authenticated, authenticatedAdmin, adminController.deleteProduct)
router.get('/admin/product/:id/edit', authenticated, authenticatedAdmin, adminController.editProduct)
router.put('/admin/product/:id', upload.single('image'), adminController.putProduct)
router.get('/admin/categories', authenticated, authenticatedAdmin, adminController.getCategories)
router.post('/admin/category', authenticated, authenticatedAdmin, adminController.addCategory)
router.get('/admin/categories/:id', authenticated, authenticatedAdmin, adminController.editCategory)
router.put('/admin/categories/:id', authenticated, authenticatedAdmin, adminController.putCategory)
router.delete('/admin/categories/:id', authenticated, authenticatedAdmin, adminController.deleteCategory)
router.get('/admin/orders', authenticated, authenticatedAdmin, adminController.getOrders)
router.get('/admin/orders/:id', authenticated, authenticatedAdmin, adminController.editOrder)
router.put('/admin/orders/:id', authenticated, authenticatedAdmin, adminController.putOrder)
router.put('/admin/orders/:id/cancel', authenticated, authenticatedAdmin, adminController.cancelOrder)

router.post('/signin', userController.signIn)
router.post('/signup', userController.signUp) 

module.exports = router