const express = require('express')
const router = express.Router()
const passport = require('../config/passport') 
const userController = require('../controllers/user-controller')
const orderController = require('../controllers/order-controller')
const products = require('./modules/prooduct')
const carts = require('./modules/cart')
const orders = require('./modules/order')
const admin = require('./modules/admin')
const { generalErrorHandler } = require('../middleware/error-handler')
const { authenticatedAdmin } = require('../middleware/auth') 
const auth = require('./modules/auth')

router.get('/', (req, res) => {
  res.render('index')
})
router.get('/signin', userController.signInPage)
router.post('/signin', passport.authenticate('local', { failureRedirect: '/signin', failureFlash: true }), userController.signIn)
router.get('/signin', userController.signInPage)
router.get('/signup', userController.signUpPage)
router.post('/signup', userController.signUp)
router.get('/logout', userController.logout)
router.post('/newebpay/callback', orderController.newebpayCallback)

router.use('/products', products)
router.use('/carts', carts)
router.use('/orders', orders)
router.use('/admin', authenticatedAdmin, admin)
router.use('/auth', auth)
router.use('/', generalErrorHandler)
module.exports = router